### PR TITLE
Regenerate parser with ANTLR 4.9.2

### PR DESCRIPTION
**Pull request by chisholm**
Regenerated the 2.0 and 2.1 pattern parsers with ANTLR 4.9.2.  The antlr4-python3-runtime python package dependency is updated to `~=4.9.0` to agree with what ANTLR itself considers a "compatible" runtime.  The parsers are also now generated with `-Dlanguage=Python3` since we no longer support python2, so python2-isms which were in the generated parser code are gone now, and results in some further changes (e.g. no more `u"..."` style unicode string literals).  I also cleaned setup.py a bit: the ANTLR runtime dependency is no longer conditional based on python version; it is redundant now that only python3+ is supported.  I added a `python_requires` to add an overall python version dependency for the library for `>=3.6`, which makes more sense.

### CODE REVIEW

**Comment by chisholm** [comment]
The python 3.9 tests failed because it's doing pre-commit stylistic checks on generated code (the parsers).  I think all style checks should be skipped for that; we should not edit it.

**Comment by clenk** [comment]
@chisholm can you add `v21/grammars` and `v20/grammars` to the exclusions in this file: https://github.com/oasis-open/cti-pattern-validator/blob/master/.pre-commit-config.yaml#L13? That should prevent the style checks on those files. We should add them as exclusions for the `trailing-whitespace` hook as well.

**Comment by chisholm** [comment]
Oh ok.  Well, the problem wasn't that values needed to be added to the existing excludes, it was that the import sorting hook didn't have any excludes.  So I added them.

**Review by clenk — APPROVED** [review]
LGTM!

**Pull request merged**
